import { SimpleGrid } from "@chakra-ui/react";
import { NoticiaItem } from "./components";

const Noticias = () => {
  const noticias = [
    {
      id: 1,
      date: new Date("2024-09-25"),
      title: "Destacada actuación de nuestros nadadores en el Cenard",
      content:
        "<p>Entre el 11 y 14 pasado se desarrolló el Campeonato de la República de Natación categoría Juveniles y Juniors en el CENARD con una nutrida y destacada participación de nuestros nadadores.</p><img src='https://picsum.photos/400/400' alt='Descripción'/><p>En el primer día de competencia, Joaquín Renzi (Loas) se consagró campeón nacional en 200m libre juvenil 2. En tanto Barbará Olguín (SAC) fue 3ra en 100m espalda juniors, Franco Gamarra (EFC) fue subcampeón en 100m espalda juniors.</p><p>En la segunda jornada la gran figura del día resultó Joaquín Renzi que se quedó con el oro en 400m libres consiguiendo el record nacional de categoría bajando por 2 segundos la marca de Gonzalo Garay Manginelli de River quién era poseedor del record.</p><p>Además Salvatore Alesio (EFC) fue campeón en 50m mariposa categoría juniors; Bárbara Olguín (SAC) 3ra en 200m espalda juniors; Tomás  Zanon (EFC) 3ro en 200m espalda juniors; Máximo Concetti (LOAS) 3ro en 400m libres juveniles 1; Matías Badaui (GER) 3er puesto en 200m pecho categoría Juvenil 1.</p><p>En la tercera jornada los podios de nuestros nadadores fueron: 2do puesto de Alesio Salvatore (EFC) en 50m libres categoría juniors; 1er puesto de Joaquín Renzi (LOAS) en 1500m libres categoría juveniles 2.</p><p>Por último, la cuarta jornada dejó otros tres podios más. Joaquín Renzi (LOAS) fue segundo en 100m libres juveniles 2; misma posición que logró Bárbara Olguín (SAC) en los 50m espalda categoría juniors y Franco Gamarra (EFC) se alzó con el oro en los 50m espalda categoría juniors.</p><p>Además de los podios, vale la pena destacar y resaltar la labor de muchos otros nadadores que alcanzaron una o más finales, colocándose entre los 8 mejores del país en esas pruebas. Ellos fueron: Sol L’ hereaux (CNSA); Franco Ledesma (CNSA); Milagros Calderón (EFC); Lía Pereyra (EFC); Candela Muñoz (CNSA); Valentino Volante (EFC); Ornella Copes (CRR); Martina Colaneri (CRR); Lucas Palminteri (EFC); Valentín Domínguez (CNSA); Valentino Racca (EFC); Milagros Moretti (LOAS); Gastón Córdoba (EFC); Facundo Luqués (GER); Julieta Nucifora (CNSA) y Joaquín De Martini (CNSA).</p><img src='https://picsum.photos/400/400' alt='Descripción'/>",
      author: "Juan Pérez",
      categories: ["Competencias", "Jóvenes"],
      url: "url_de_la_noticia.html",
    },
    {
      id: 2,
      date: new Date("2024-09-25"),
      title: "Destacada actuación de nuestros nadadores en el Cenard",
      content:
        "<p>Entre el 11 y 14 pasado se desarrolló el Campeonato de la República de Natación categoría Juveniles y Juniors en el CENARD con una nutrida y destacada participación de nuestros nadadores.</p><img src='https://picsum.photos/400/400' alt='Descripción'/><p>En el primer día de competencia, Joaquín Renzi (Loas) se consagró campeón nacional en 200m libre juvenil 2. En tanto Barbará Olguín (SAC) fue 3ra en 100m espalda juniors, Franco Gamarra (EFC) fue subcampeón en 100m espalda juniors.</p><p>En la segunda jornada la gran figura del día resultó Joaquín Renzi que se quedó con el oro en 400m libres consiguiendo el record nacional de categoría bajando por 2 segundos la marca de Gonzalo Garay Manginelli de River quién era poseedor del record.</p><p>Además Salvatore Alesio (EFC) fue campeón en 50m mariposa categoría juniors; Bárbara Olguín (SAC) 3ra en 200m espalda juniors; Tomás  Zanon (EFC) 3ro en 200m espalda juniors; Máximo Concetti (LOAS) 3ro en 400m libres juveniles 1; Matías Badaui (GER) 3er puesto en 200m pecho categoría Juvenil 1.</p><p>En la tercera jornada los podios de nuestros nadadores fueron: 2do puesto de Alesio Salvatore (EFC) en 50m libres categoría juniors; 1er puesto de Joaquín Renzi (LOAS) en 1500m libres categoría juveniles 2.</p><p>Por último, la cuarta jornada dejó otros tres podios más. Joaquín Renzi (LOAS) fue segundo en 100m libres juveniles 2; misma posición que logró Bárbara Olguín (SAC) en los 50m espalda categoría juniors y Franco Gamarra (EFC) se alzó con el oro en los 50m espalda categoría juniors.</p><p>Además de los podios, vale la pena destacar y resaltar la labor de muchos otros nadadores que alcanzaron una o más finales, colocándose entre los 8 mejores del país en esas pruebas. Ellos fueron: Sol L’ hereaux (CNSA); Franco Ledesma (CNSA); Milagros Calderón (EFC); Lía Pereyra (EFC); Candela Muñoz (CNSA); Valentino Volante (EFC); Ornella Copes (CRR); Martina Colaneri (CRR); Lucas Palminteri (EFC); Valentín Domínguez (CNSA); Valentino Racca (EFC); Milagros Moretti (LOAS); Gastón Córdoba (EFC); Facundo Luqués (GER); Julieta Nucifora (CNSA) y Joaquín De Martini (CNSA).</p><img src='https://picsum.photos/400/400' alt='Descripción'/>",
      author: "Juan Pérez",
      categories: ["Competencias", "Jóvenes"],
      url: "url_de_la_noticia.html",
    },
    {
      id: 3,
      date: new Date("2024-09-25"),
      title: "Destacada actuación de nuestros nadadores en el Cenard",
      content:
        "<p>Entre el 11 y 14 pasado se desarrolló el Campeonato de la República de Natación categoría Juveniles y Juniors en el CENARD con una nutrida y destacada participación de nuestros nadadores.</p><img src='https://picsum.photos/400/400' alt='Descripción'/><p>En el primer día de competencia, Joaquín Renzi (Loas) se consagró campeón nacional en 200m libre juvenil 2. En tanto Barbará Olguín (SAC) fue 3ra en 100m espalda juniors, Franco Gamarra (EFC) fue subcampeón en 100m espalda juniors.</p><p>En la segunda jornada la gran figura del día resultó Joaquín Renzi que se quedó con el oro en 400m libres consiguiendo el record nacional de categoría bajando por 2 segundos la marca de Gonzalo Garay Manginelli de River quién era poseedor del record.</p><p>Además Salvatore Alesio (EFC) fue campeón en 50m mariposa categoría juniors; Bárbara Olguín (SAC) 3ra en 200m espalda juniors; Tomás  Zanon (EFC) 3ro en 200m espalda juniors; Máximo Concetti (LOAS) 3ro en 400m libres juveniles 1; Matías Badaui (GER) 3er puesto en 200m pecho categoría Juvenil 1.</p><p>En la tercera jornada los podios de nuestros nadadores fueron: 2do puesto de Alesio Salvatore (EFC) en 50m libres categoría juniors; 1er puesto de Joaquín Renzi (LOAS) en 1500m libres categoría juveniles 2.</p><p>Por último, la cuarta jornada dejó otros tres podios más. Joaquín Renzi (LOAS) fue segundo en 100m libres juveniles 2; misma posición que logró Bárbara Olguín (SAC) en los 50m espalda categoría juniors y Franco Gamarra (EFC) se alzó con el oro en los 50m espalda categoría juniors.</p><p>Además de los podios, vale la pena destacar y resaltar la labor de muchos otros nadadores que alcanzaron una o más finales, colocándose entre los 8 mejores del país en esas pruebas. Ellos fueron: Sol L’ hereaux (CNSA); Franco Ledesma (CNSA); Milagros Calderón (EFC); Lía Pereyra (EFC); Candela Muñoz (CNSA); Valentino Volante (EFC); Ornella Copes (CRR); Martina Colaneri (CRR); Lucas Palminteri (EFC); Valentín Domínguez (CNSA); Valentino Racca (EFC); Milagros Moretti (LOAS); Gastón Córdoba (EFC); Facundo Luqués (GER); Julieta Nucifora (CNSA) y Joaquín De Martini (CNSA).</p><img src='https://picsum.photos/400/400' alt='Descripción'/>",
      author: "Juan Pérez",
      categories: ["Competencias", "Jóvenes"],
      url: "url_de_la_noticia.html",
    },
    {
      id: 4,
      date: new Date("2024-09-25"),
      title: "Destacada actuación de nuestros nadadores en el Cenard",
      content:
        "<p>Entre el 11 y 14 pasado se desarrolló el Campeonato de la República de Natación categoría Juveniles y Juniors en el CENARD con una nutrida y destacada participación de nuestros nadadores.</p><img src='https://picsum.photos/400/400' alt='Descripción'/><p>En el primer día de competencia, Joaquín Renzi (Loas) se consagró campeón nacional en 200m libre juvenil 2. En tanto Barbará Olguín (SAC) fue 3ra en 100m espalda juniors, Franco Gamarra (EFC) fue subcampeón en 100m espalda juniors.</p><p>En la segunda jornada la gran figura del día resultó Joaquín Renzi que se quedó con el oro en 400m libres consiguiendo el record nacional de categoría bajando por 2 segundos la marca de Gonzalo Garay Manginelli de River quién era poseedor del record.</p><p>Además Salvatore Alesio (EFC) fue campeón en 50m mariposa categoría juniors; Bárbara Olguín (SAC) 3ra en 200m espalda juniors; Tomás  Zanon (EFC) 3ro en 200m espalda juniors; Máximo Concetti (LOAS) 3ro en 400m libres juveniles 1; Matías Badaui (GER) 3er puesto en 200m pecho categoría Juvenil 1.</p><p>En la tercera jornada los podios de nuestros nadadores fueron: 2do puesto de Alesio Salvatore (EFC) en 50m libres categoría juniors; 1er puesto de Joaquín Renzi (LOAS) en 1500m libres categoría juveniles 2.</p><p>Por último, la cuarta jornada dejó otros tres podios más. Joaquín Renzi (LOAS) fue segundo en 100m libres juveniles 2; misma posición que logró Bárbara Olguín (SAC) en los 50m espalda categoría juniors y Franco Gamarra (EFC) se alzó con el oro en los 50m espalda categoría juniors.</p><p>Además de los podios, vale la pena destacar y resaltar la labor de muchos otros nadadores que alcanzaron una o más finales, colocándose entre los 8 mejores del país en esas pruebas. Ellos fueron: Sol L’ hereaux (CNSA); Franco Ledesma (CNSA); Milagros Calderón (EFC); Lía Pereyra (EFC); Candela Muñoz (CNSA); Valentino Volante (EFC); Ornella Copes (CRR); Martina Colaneri (CRR); Lucas Palminteri (EFC); Valentín Domínguez (CNSA); Valentino Racca (EFC); Milagros Moretti (LOAS); Gastón Córdoba (EFC); Facundo Luqués (GER); Julieta Nucifora (CNSA) y Joaquín De Martini (CNSA).</p><img src='https://picsum.photos/400/400' alt='Descripción'/>",
      author: "Juan Pérez",
      categories: ["Competencias", "Jóvenes"],
      url: "url_de_la_noticia.html",
    },
    {
      id: 5,
      date: new Date("2024-09-25"),
      title: "Destacada actuación de nuestros nadadores en el Cenard",
      content:
        "<p>Entre el 11 y 14 pasado se desarrolló el Campeonato de la República de Natación categoría Juveniles y Juniors en el CENARD con una nutrida y destacada participación de nuestros nadadores.</p><img src='https://picsum.photos/400/400' alt='Descripción'/><p>En el primer día de competencia, Joaquín Renzi (Loas) se consagró campeón nacional en 200m libre juvenil 2. En tanto Barbará Olguín (SAC) fue 3ra en 100m espalda juniors, Franco Gamarra (EFC) fue subcampeón en 100m espalda juniors.</p><p>En la segunda jornada la gran figura del día resultó Joaquín Renzi que se quedó con el oro en 400m libres consiguiendo el record nacional de categoría bajando por 2 segundos la marca de Gonzalo Garay Manginelli de River quién era poseedor del record.</p><p>Además Salvatore Alesio (EFC) fue campeón en 50m mariposa categoría juniors; Bárbara Olguín (SAC) 3ra en 200m espalda juniors; Tomás  Zanon (EFC) 3ro en 200m espalda juniors; Máximo Concetti (LOAS) 3ro en 400m libres juveniles 1; Matías Badaui (GER) 3er puesto en 200m pecho categoría Juvenil 1.</p><p>En la tercera jornada los podios de nuestros nadadores fueron: 2do puesto de Alesio Salvatore (EFC) en 50m libres categoría juniors; 1er puesto de Joaquín Renzi (LOAS) en 1500m libres categoría juveniles 2.</p><p>Por último, la cuarta jornada dejó otros tres podios más. Joaquín Renzi (LOAS) fue segundo en 100m libres juveniles 2; misma posición que logró Bárbara Olguín (SAC) en los 50m espalda categoría juniors y Franco Gamarra (EFC) se alzó con el oro en los 50m espalda categoría juniors.</p><p>Además de los podios, vale la pena destacar y resaltar la labor de muchos otros nadadores que alcanzaron una o más finales, colocándose entre los 8 mejores del país en esas pruebas. Ellos fueron: Sol L’ hereaux (CNSA); Franco Ledesma (CNSA); Milagros Calderón (EFC); Lía Pereyra (EFC); Candela Muñoz (CNSA); Valentino Volante (EFC); Ornella Copes (CRR); Martina Colaneri (CRR); Lucas Palminteri (EFC); Valentín Domínguez (CNSA); Valentino Racca (EFC); Milagros Moretti (LOAS); Gastón Córdoba (EFC); Facundo Luqués (GER); Julieta Nucifora (CNSA) y Joaquín De Martini (CNSA).</p><img src='https://picsum.photos/400/400' alt='Descripción'/>",
      author: "Juan Pérez",
      categories: ["Competencias", "Jóvenes"],
      url: "url_de_la_noticia.html",
    },
    {
      id: 6,
      date: new Date("2024-09-25"),
      title: "Destacada actuación de nuestros nadadores en el Cenard",
      content:
        "<p>Entre el 11 y 14 pasado se desarrolló el Campeonato de la República de Natación categoría Juveniles y Juniors en el CENARD con una nutrida y destacada participación de nuestros nadadores.</p><img src='https://picsum.photos/400/400' alt='Descripción'/><p>En el primer día de competencia, Joaquín Renzi (Loas) se consagró campeón nacional en 200m libre juvenil 2. En tanto Barbará Olguín (SAC) fue 3ra en 100m espalda juniors, Franco Gamarra (EFC) fue subcampeón en 100m espalda juniors.</p><p>En la segunda jornada la gran figura del día resultó Joaquín Renzi que se quedó con el oro en 400m libres consiguiendo el record nacional de categoría bajando por 2 segundos la marca de Gonzalo Garay Manginelli de River quién era poseedor del record.</p><p>Además Salvatore Alesio (EFC) fue campeón en 50m mariposa categoría juniors; Bárbara Olguín (SAC) 3ra en 200m espalda juniors; Tomás  Zanon (EFC) 3ro en 200m espalda juniors; Máximo Concetti (LOAS) 3ro en 400m libres juveniles 1; Matías Badaui (GER) 3er puesto en 200m pecho categoría Juvenil 1.</p><p>En la tercera jornada los podios de nuestros nadadores fueron: 2do puesto de Alesio Salvatore (EFC) en 50m libres categoría juniors; 1er puesto de Joaquín Renzi (LOAS) en 1500m libres categoría juveniles 2.</p><p>Por último, la cuarta jornada dejó otros tres podios más. Joaquín Renzi (LOAS) fue segundo en 100m libres juveniles 2; misma posición que logró Bárbara Olguín (SAC) en los 50m espalda categoría juniors y Franco Gamarra (EFC) se alzó con el oro en los 50m espalda categoría juniors.</p><p>Además de los podios, vale la pena destacar y resaltar la labor de muchos otros nadadores que alcanzaron una o más finales, colocándose entre los 8 mejores del país en esas pruebas. Ellos fueron: Sol L’ hereaux (CNSA); Franco Ledesma (CNSA); Milagros Calderón (EFC); Lía Pereyra (EFC); Candela Muñoz (CNSA); Valentino Volante (EFC); Ornella Copes (CRR); Martina Colaneri (CRR); Lucas Palminteri (EFC); Valentín Domínguez (CNSA); Valentino Racca (EFC); Milagros Moretti (LOAS); Gastón Córdoba (EFC); Facundo Luqués (GER); Julieta Nucifora (CNSA) y Joaquín De Martini (CNSA).</p><img src='https://picsum.photos/400/400' alt='Descripción'/>",
      author: "Juan Pérez",
      categories: ["Competencias", "Jóvenes"],
      url: "url_de_la_noticia.html",
    },
    {
      id: 7,
      date: new Date("2024-09-25"),
      title: "Destacada actuación de nuestros nadadores en el Cenard",
      content:
        "<p>Entre el 11 y 14 pasado se desarrolló el Campeonato de la República de Natación categoría Juveniles y Juniors en el CENARD con una nutrida y destacada participación de nuestros nadadores.</p><img src='https://picsum.photos/400/400' alt='Descripción'/><p>En el primer día de competencia, Joaquín Renzi (Loas) se consagró campeón nacional en 200m libre juvenil 2. En tanto Barbará Olguín (SAC) fue 3ra en 100m espalda juniors, Franco Gamarra (EFC) fue subcampeón en 100m espalda juniors.</p><p>En la segunda jornada la gran figura del día resultó Joaquín Renzi que se quedó con el oro en 400m libres consiguiendo el record nacional de categoría bajando por 2 segundos la marca de Gonzalo Garay Manginelli de River quién era poseedor del record.</p><p>Además Salvatore Alesio (EFC) fue campeón en 50m mariposa categoría juniors; Bárbara Olguín (SAC) 3ra en 200m espalda juniors; Tomás  Zanon (EFC) 3ro en 200m espalda juniors; Máximo Concetti (LOAS) 3ro en 400m libres juveniles 1; Matías Badaui (GER) 3er puesto en 200m pecho categoría Juvenil 1.</p><p>En la tercera jornada los podios de nuestros nadadores fueron: 2do puesto de Alesio Salvatore (EFC) en 50m libres categoría juniors; 1er puesto de Joaquín Renzi (LOAS) en 1500m libres categoría juveniles 2.</p><p>Por último, la cuarta jornada dejó otros tres podios más. Joaquín Renzi (LOAS) fue segundo en 100m libres juveniles 2; misma posición que logró Bárbara Olguín (SAC) en los 50m espalda categoría juniors y Franco Gamarra (EFC) se alzó con el oro en los 50m espalda categoría juniors.</p><p>Además de los podios, vale la pena destacar y resaltar la labor de muchos otros nadadores que alcanzaron una o más finales, colocándose entre los 8 mejores del país en esas pruebas. Ellos fueron: Sol L’ hereaux (CNSA); Franco Ledesma (CNSA); Milagros Calderón (EFC); Lía Pereyra (EFC); Candela Muñoz (CNSA); Valentino Volante (EFC); Ornella Copes (CRR); Martina Colaneri (CRR); Lucas Palminteri (EFC); Valentín Domínguez (CNSA); Valentino Racca (EFC); Milagros Moretti (LOAS); Gastón Córdoba (EFC); Facundo Luqués (GER); Julieta Nucifora (CNSA) y Joaquín De Martini (CNSA).</p><img src='https://picsum.photos/400/400' alt='Descripción'/>",
      author: "Juan Pérez",
      categories: ["Competencias", "Jóvenes"],
      url: "url_de_la_noticia.html",
    },
    {
      id: 8,
      date: new Date("2024-09-25"),
      title: "Destacada actuación de nuestros nadadores en el Cenard",
      content:
        "<p>Entre el 11 y 14 pasado se desarrolló el Campeonato de la República de Natación categoría Juveniles y Juniors en el CENARD con una nutrida y destacada participación de nuestros nadadores.</p><img src='https://picsum.photos/400/400' alt='Descripción'/><p>En el primer día de competencia, Joaquín Renzi (Loas) se consagró campeón nacional en 200m libre juvenil 2. En tanto Barbará Olguín (SAC) fue 3ra en 100m espalda juniors, Franco Gamarra (EFC) fue subcampeón en 100m espalda juniors.</p><p>En la segunda jornada la gran figura del día resultó Joaquín Renzi que se quedó con el oro en 400m libres consiguiendo el record nacional de categoría bajando por 2 segundos la marca de Gonzalo Garay Manginelli de River quién era poseedor del record.</p><p>Además Salvatore Alesio (EFC) fue campeón en 50m mariposa categoría juniors; Bárbara Olguín (SAC) 3ra en 200m espalda juniors; Tomás  Zanon (EFC) 3ro en 200m espalda juniors; Máximo Concetti (LOAS) 3ro en 400m libres juveniles 1; Matías Badaui (GER) 3er puesto en 200m pecho categoría Juvenil 1.</p><p>En la tercera jornada los podios de nuestros nadadores fueron: 2do puesto de Alesio Salvatore (EFC) en 50m libres categoría juniors; 1er puesto de Joaquín Renzi (LOAS) en 1500m libres categoría juveniles 2.</p><p>Por último, la cuarta jornada dejó otros tres podios más. Joaquín Renzi (LOAS) fue segundo en 100m libres juveniles 2; misma posición que logró Bárbara Olguín (SAC) en los 50m espalda categoría juniors y Franco Gamarra (EFC) se alzó con el oro en los 50m espalda categoría juniors.</p><p>Además de los podios, vale la pena destacar y resaltar la labor de muchos otros nadadores que alcanzaron una o más finales, colocándose entre los 8 mejores del país en esas pruebas. Ellos fueron: Sol L’ hereaux (CNSA); Franco Ledesma (CNSA); Milagros Calderón (EFC); Lía Pereyra (EFC); Candela Muñoz (CNSA); Valentino Volante (EFC); Ornella Copes (CRR); Martina Colaneri (CRR); Lucas Palminteri (EFC); Valentín Domínguez (CNSA); Valentino Racca (EFC); Milagros Moretti (LOAS); Gastón Córdoba (EFC); Facundo Luqués (GER); Julieta Nucifora (CNSA) y Joaquín De Martini (CNSA).</p><img src='https://picsum.photos/400/400' alt='Descripción'/>",
      author: "Juan Pérez",
      categories: ["Competencias", "Jóvenes"],
      url: "url_de_la_noticia.html",
    },
    {
      id: 9,
      date: new Date("2024-09-25"),
      title: "Destacada actuación de nuestros nadadores en el Cenard",
      content:
        "<p>Entre el 11 y 14 pasado se desarrolló el Campeonato de la República de Natación categoría Juveniles y Juniors en el CENARD con una nutrida y destacada participación de nuestros nadadores.</p><img src='https://picsum.photos/400/400' alt='Descripción'/><p>En el primer día de competencia, Joaquín Renzi (Loas) se consagró campeón nacional en 200m libre juvenil 2. En tanto Barbará Olguín (SAC) fue 3ra en 100m espalda juniors, Franco Gamarra (EFC) fue subcampeón en 100m espalda juniors.</p><p>En la segunda jornada la gran figura del día resultó Joaquín Renzi que se quedó con el oro en 400m libres consiguiendo el record nacional de categoría bajando por 2 segundos la marca de Gonzalo Garay Manginelli de River quién era poseedor del record.</p><p>Además Salvatore Alesio (EFC) fue campeón en 50m mariposa categoría juniors; Bárbara Olguín (SAC) 3ra en 200m espalda juniors; Tomás  Zanon (EFC) 3ro en 200m espalda juniors; Máximo Concetti (LOAS) 3ro en 400m libres juveniles 1; Matías Badaui (GER) 3er puesto en 200m pecho categoría Juvenil 1.</p><p>En la tercera jornada los podios de nuestros nadadores fueron: 2do puesto de Alesio Salvatore (EFC) en 50m libres categoría juniors; 1er puesto de Joaquín Renzi (LOAS) en 1500m libres categoría juveniles 2.</p><p>Por último, la cuarta jornada dejó otros tres podios más. Joaquín Renzi (LOAS) fue segundo en 100m libres juveniles 2; misma posición que logró Bárbara Olguín (SAC) en los 50m espalda categoría juniors y Franco Gamarra (EFC) se alzó con el oro en los 50m espalda categoría juniors.</p><p>Además de los podios, vale la pena destacar y resaltar la labor de muchos otros nadadores que alcanzaron una o más finales, colocándose entre los 8 mejores del país en esas pruebas. Ellos fueron: Sol L’ hereaux (CNSA); Franco Ledesma (CNSA); Milagros Calderón (EFC); Lía Pereyra (EFC); Candela Muñoz (CNSA); Valentino Volante (EFC); Ornella Copes (CRR); Martina Colaneri (CRR); Lucas Palminteri (EFC); Valentín Domínguez (CNSA); Valentino Racca (EFC); Milagros Moretti (LOAS); Gastón Córdoba (EFC); Facundo Luqués (GER); Julieta Nucifora (CNSA) y Joaquín De Martini (CNSA).</p><img src='https://picsum.photos/400/400' alt='Descripción'/>",
      author: "Juan Pérez",
      categories: ["Competencias", "Jóvenes"],
      url: "url_de_la_noticia.html",
    },
    {
      id: 10,
      date: new Date("2024-09-25"),
      title: "Destacada actuación de nuestros nadadores en el Cenard",
      content:
        "<p>Entre el 11 y 14 pasado se desarrolló el Campeonato de la República de Natación categoría Juveniles y Juniors en el CENARD con una nutrida y destacada participación de nuestros nadadores.</p><img src='https://picsum.photos/400/400' alt='Descripción'/><p>En el primer día de competencia, Joaquín Renzi (Loas) se consagró campeón nacional en 200m libre juvenil 2. En tanto Barbará Olguín (SAC) fue 3ra en 100m espalda juniors, Franco Gamarra (EFC) fue subcampeón en 100m espalda juniors.</p><p>En la segunda jornada la gran figura del día resultó Joaquín Renzi que se quedó con el oro en 400m libres consiguiendo el record nacional de categoría bajando por 2 segundos la marca de Gonzalo Garay Manginelli de River quién era poseedor del record.</p><p>Además Salvatore Alesio (EFC) fue campeón en 50m mariposa categoría juniors; Bárbara Olguín (SAC) 3ra en 200m espalda juniors; Tomás  Zanon (EFC) 3ro en 200m espalda juniors; Máximo Concetti (LOAS) 3ro en 400m libres juveniles 1; Matías Badaui (GER) 3er puesto en 200m pecho categoría Juvenil 1.</p><p>En la tercera jornada los podios de nuestros nadadores fueron: 2do puesto de Alesio Salvatore (EFC) en 50m libres categoría juniors; 1er puesto de Joaquín Renzi (LOAS) en 1500m libres categoría juveniles 2.</p><p>Por último, la cuarta jornada dejó otros tres podios más. Joaquín Renzi (LOAS) fue segundo en 100m libres juveniles 2; misma posición que logró Bárbara Olguín (SAC) en los 50m espalda categoría juniors y Franco Gamarra (EFC) se alzó con el oro en los 50m espalda categoría juniors.</p><p>Además de los podios, vale la pena destacar y resaltar la labor de muchos otros nadadores que alcanzaron una o más finales, colocándose entre los 8 mejores del país en esas pruebas. Ellos fueron: Sol L’ hereaux (CNSA); Franco Ledesma (CNSA); Milagros Calderón (EFC); Lía Pereyra (EFC); Candela Muñoz (CNSA); Valentino Volante (EFC); Ornella Copes (CRR); Martina Colaneri (CRR); Lucas Palminteri (EFC); Valentín Domínguez (CNSA); Valentino Racca (EFC); Milagros Moretti (LOAS); Gastón Córdoba (EFC); Facundo Luqués (GER); Julieta Nucifora (CNSA) y Joaquín De Martini (CNSA).</p><img src='https://picsum.photos/400/400' alt='Descripción'/>",
      author: "Juan Pérez",
      categories: ["Competencias", "Jóvenes"],
      url: "url_de_la_noticia.html",
    },
    {
      id: 11,
      date: new Date("2024-09-25"),
      title: "Destacada actuación de nuestros nadadores en el Cenard",
      content:
        "<p>Entre el 11 y 14 pasado se desarrolló el Campeonato de la República de Natación categoría Juveniles y Juniors en el CENARD con una nutrida y destacada participación de nuestros nadadores.</p><img src='https://picsum.photos/400/400' alt='Descripción'/><p>En el primer día de competencia, Joaquín Renzi (Loas) se consagró campeón nacional en 200m libre juvenil 2. En tanto Barbará Olguín (SAC) fue 3ra en 100m espalda juniors, Franco Gamarra (EFC) fue subcampeón en 100m espalda juniors.</p><p>En la segunda jornada la gran figura del día resultó Joaquín Renzi que se quedó con el oro en 400m libres consiguiendo el record nacional de categoría bajando por 2 segundos la marca de Gonzalo Garay Manginelli de River quién era poseedor del record.</p><p>Además Salvatore Alesio (EFC) fue campeón en 50m mariposa categoría juniors; Bárbara Olguín (SAC) 3ra en 200m espalda juniors; Tomás  Zanon (EFC) 3ro en 200m espalda juniors; Máximo Concetti (LOAS) 3ro en 400m libres juveniles 1; Matías Badaui (GER) 3er puesto en 200m pecho categoría Juvenil 1.</p><p>En la tercera jornada los podios de nuestros nadadores fueron: 2do puesto de Alesio Salvatore (EFC) en 50m libres categoría juniors; 1er puesto de Joaquín Renzi (LOAS) en 1500m libres categoría juveniles 2.</p><p>Por último, la cuarta jornada dejó otros tres podios más. Joaquín Renzi (LOAS) fue segundo en 100m libres juveniles 2; misma posición que logró Bárbara Olguín (SAC) en los 50m espalda categoría juniors y Franco Gamarra (EFC) se alzó con el oro en los 50m espalda categoría juniors.</p><p>Además de los podios, vale la pena destacar y resaltar la labor de muchos otros nadadores que alcanzaron una o más finales, colocándose entre los 8 mejores del país en esas pruebas. Ellos fueron: Sol L’ hereaux (CNSA); Franco Ledesma (CNSA); Milagros Calderón (EFC); Lía Pereyra (EFC); Candela Muñoz (CNSA); Valentino Volante (EFC); Ornella Copes (CRR); Martina Colaneri (CRR); Lucas Palminteri (EFC); Valentín Domínguez (CNSA); Valentino Racca (EFC); Milagros Moretti (LOAS); Gastón Córdoba (EFC); Facundo Luqués (GER); Julieta Nucifora (CNSA) y Joaquín De Martini (CNSA).</p><img src='https://picsum.photos/400/400' alt='Descripción'/>",
      author: "Juan Pérez",
      categories: ["Competencias", "Jóvenes"],
      url: "url_de_la_noticia.html",
    },
    {
      id: 12,
      date: new Date("2024-09-25"),
      title: "Destacada actuación de nuestros nadadores en el Cenard",
      content:
        "<p>Entre el 11 y 14 pasado se desarrolló el Campeonato de la República de Natación categoría Juveniles y Juniors en el CENARD con una nutrida y destacada participación de nuestros nadadores.</p><img src='https://picsum.photos/400/400' alt='Descripción'/><p>En el primer día de competencia, Joaquín Renzi (Loas) se consagró campeón nacional en 200m libre juvenil 2. En tanto Barbará Olguín (SAC) fue 3ra en 100m espalda juniors, Franco Gamarra (EFC) fue subcampeón en 100m espalda juniors.</p><p>En la segunda jornada la gran figura del día resultó Joaquín Renzi que se quedó con el oro en 400m libres consiguiendo el record nacional de categoría bajando por 2 segundos la marca de Gonzalo Garay Manginelli de River quién era poseedor del record.</p><p>Además Salvatore Alesio (EFC) fue campeón en 50m mariposa categoría juniors; Bárbara Olguín (SAC) 3ra en 200m espalda juniors; Tomás  Zanon (EFC) 3ro en 200m espalda juniors; Máximo Concetti (LOAS) 3ro en 400m libres juveniles 1; Matías Badaui (GER) 3er puesto en 200m pecho categoría Juvenil 1.</p><p>En la tercera jornada los podios de nuestros nadadores fueron: 2do puesto de Alesio Salvatore (EFC) en 50m libres categoría juniors; 1er puesto de Joaquín Renzi (LOAS) en 1500m libres categoría juveniles 2.</p><p>Por último, la cuarta jornada dejó otros tres podios más. Joaquín Renzi (LOAS) fue segundo en 100m libres juveniles 2; misma posición que logró Bárbara Olguín (SAC) en los 50m espalda categoría juniors y Franco Gamarra (EFC) se alzó con el oro en los 50m espalda categoría juniors.</p><p>Además de los podios, vale la pena destacar y resaltar la labor de muchos otros nadadores que alcanzaron una o más finales, colocándose entre los 8 mejores del país en esas pruebas. Ellos fueron: Sol L’ hereaux (CNSA); Franco Ledesma (CNSA); Milagros Calderón (EFC); Lía Pereyra (EFC); Candela Muñoz (CNSA); Valentino Volante (EFC); Ornella Copes (CRR); Martina Colaneri (CRR); Lucas Palminteri (EFC); Valentín Domínguez (CNSA); Valentino Racca (EFC); Milagros Moretti (LOAS); Gastón Córdoba (EFC); Facundo Luqués (GER); Julieta Nucifora (CNSA) y Joaquín De Martini (CNSA).</p><img src='https://picsum.photos/400/400' alt='Descripción'/>",
      author: "Juan Pérez",
      categories: ["Competencias", "Jóvenes"],
      url: "url_de_la_noticia.html",
    },
  ];

  return (
    <SimpleGrid columns={{ base: 1, md: 2, lg: 3 }} spacing={8} p={5}>
      {noticias.map((noticia) => (
        <NoticiaItem key={noticia.id} noticia={noticia} />
      ))}
    </SimpleGrid>
  );
};

export default Noticias;
